---

language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
before_script:
  - yamllint .
  - ansible-lint .
script:
  - molecule test -- --skip-tags "register-agent"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
