---

# Verifying whether the activation code and activation id have been provided.
- name: Verify whether the activation code and activation id have been provided.
  fail:
    msg: >
      The SSM activation code or SSM activation id were provided when auto_activation
      is set as enabled. These two parameters are conflictual, please review the provided
      Ansible parameters to ensure that you select the manual or automatic activation.
  when: "aws_ssm_activation_code is defined or aws_ssm_activation_id is defined"

# Detecting the current AWS Region to use.
- include: region-detect/main.yml
  when: aws_ssm_ec2_region is not defined

# Creating a new IAM Managed policy to be attached to
# the IAM Role associated with managed instances.
- name: Create a new IAM Managed Policy for managed instances
  iam_managed_policy:
    policy_name: "{{ aws_ssm_default_iam_managed_policy }}"
    policy_description: An IAM managed policy to be attached to the IAM Role associated with AWS SSM managed instances.
    policy: "{{ lookup('template', 'managed_policy.j2') }}"
    state: present
  become: false
  delegate_to: localhost
  register: iam_managed_policy
  when: aws_ssm_iam_role is not defined

# Creating a new IAM Role for managed instances.
- name: Create a new IAM Role for managed instances
  iam_role:
    name: "{{ aws_ssm_default_iam_role_name }}"
    assume_role_policy_document: "{{ lookup('file', 'assume-role-policy.json') }}"
    description: Default IAM Role associated with AWS SSM managed instances.
    purge_policies: true
    managed_policy:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - "{{ iam_managed_policy.policy.arn }}"
  become: false
  delegate_to: localhost
  register: role
  when: aws_ssm_iam_role is not defined

# Waiting for the role to propagate.
- name: Waiting for the role to propagate
  pause:
    seconds: 10
  when: role.changed

# Setting the created AWS role for Ansible managed instances.
- name: Set the created AWS role for Ansible managed instances
  set_fact:
    aws_ssm_iam_role: "{{ role.iam_role.role_name }}"
  when: aws_ssm_iam_role is not defined

# Setting the default instance tags as a fact.
- name: Set the default instance tags as a fact
  set_fact:
    instance_tags: "Key=provisioning-tool,Value=ansible-ssm"
  when: instance_tags is not defined

# Generates a new activation code.
- name: Generating a new activation code
  command: >
    aws ssm create-activation
      --description "A new activation created by 'ansible-ssm' for '{{ ansible_hostname }}'."
      --default-instance-name "{{ default_instance_name }}"
      --iam-role "{{ aws_ssm_iam_role }}"
      --registration-limit 1
      --tags {{ instance_tags }}
  become: false
  delegate_to: localhost
  register: aws_activation_parameters

# Setting the AWS activation parameters as fact.
- name: Sets the AWS activation parameters as fact
  set_fact:
    aws_ssm_activation_code: "{{ aws_activation_parameters.stdout | from_json | json_query('ActivationCode') }}"
    aws_ssm_activation_id: "{{ aws_activation_parameters.stdout | from_json | json_query('ActivationId') }}"
