---

# Including the role variables if a package manager is available.
- name: Include OS-specific variables when a package manager is available
  include_vars: "{{ ansible_os_family }}.yml"
  when: package_manager_available

# Including the role variables if there are no package manager.
- name: Include specific variables when no package manager is available
  include_vars: "Manual.yml"
  when: not package_manager_available

# Verifying whether the current architecture is supported.
- name: Verify whether the current architecture is supported.
  fail:
    msg: >
      The current architecture '{{ ansible_architecture }}' is not supported
      by the AWS SSM Agent on the current operating system. Please refer to the
      https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-manual-agent-install.html
      page for more information on supported architectures.
  when: "ansible_architecture not in architecture_map | list"

# Saving the architecture name.
- name: Save the architecture name
  set_fact:
    arch_name: "{{ architecture_map[ansible_architecture].value }}"

# Install the agent given the OS and architecture.
- include_tasks: "{{ ansible_os_family }}.yml"
  when: package_manager_available == true

# Install the agent manually when no package manager is available.
- include_tasks: Manual.yml
  when: package_manager_available != true
